{% set name = "iso3166" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c420a66a71ae18ae280342eedf4cd67aa40e83b23e36cce3e6979a2a5b79afd9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - iso3166

about:
  home: https://github.com/deactivated/python-iso3166
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Standalone ISO 3166-1 country definitions

  description: |
    ISO 3166-1 defines two-letter, three-letter, and three-digit country codes.
    python-iso3166 is a self-contained module that converts between these codes
    and the corresponding country name.
  dev_url: https://github.com/deactivated/python-iso3166

extra:
  recipe-maintainers:
    - johnhany97
